///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ANA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ANARepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("03a5e1f6-ad4f-4699-9c4f-29b56a6c6347")]
    public partial class ANARepository : RepoGenBaseFolder
    {
        static ANARepository instance = new ANARepository();
        ANARepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        ANARepositoryFolders.ProfileFolder _profile;
        ANARepositoryFolders.LoginAppFolder _login;
        ANARepositoryFolders.SelectingOptionInASelectListDropAppFolder _selectingoptioninaselectlistdrop;
        ANARepositoryFolders.DropdownAppFolder _dropdown;
        RepoItemInfo _lastnameInfo;
        RepoItemInfo _firstnameInfo;
        RepoItemInfo _addressfield1Info;
        RepoItemInfo _cityInfo;
        RepoItemInfo _zipcodeInfo;
        RepoItemInfo _phone1Info;
        RepoItemInfo _phone2Info;
        RepoItemInfo _phone3Info;
        RepoItemInfo _newpasswordInfo;
        RepoItemInfo _confirmpasswordInfo;
        RepoItemInfo _positiondescriptionInfo;
        RepoItemInfo _advancedpracticeInfo;
        RepoItemInfo _userregnextInfo;
        RepoItemInfo _txtemailInfo;
        RepoItemInfo _btnnextInfo;

        /// <summary>
        /// Gets the singleton class instance representing the ANARepository element repository.
        /// </summary>
        [RepositoryFolder("03a5e1f6-ad4f-4699-9c4f-29b56a6c6347")]
        public static ANARepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ANARepository() 
            : base("ANARepository", "/", null, 0, false, "03a5e1f6-ad4f-4699-9c4f-29b56a6c6347", ".\\RepositoryImages\\ANARepository03a5e1f6.rximgres")
        {
            _applicationundertest = new ANARepositoryFolders.ApplicationUnderTestAppFolder(this);
            _profile = new ANARepositoryFolders.ProfileFolder(this);
            _login = new ANARepositoryFolders.LoginAppFolder(this);
            _selectingoptioninaselectlistdrop = new ANARepositoryFolders.SelectingOptionInASelectListDropAppFolder(this);
            _dropdown = new ANARepositoryFolders.DropdownAppFolder(this);
            _lastnameInfo = new RepoItemInfo(this, "Lastname", "/dom[@domain='test.nursingworld.org']//input[#'lastname']", 30000, null, "908e1e9d-3481-4733-8b76-66c06151cafd");
            _firstnameInfo = new RepoItemInfo(this, "Firstname", "/dom[@domain='test.nursingworld.org']//input[#'firstname']", 30000, null, "c6d7db9f-f414-4d98-b2d0-e90913ae1a05");
            _addressfield1Info = new RepoItemInfo(this, "AddressField1", "/dom[@domain='test.nursingworld.org']//div[#'address']/?/?/input[@type='text']", 30000, null, "01a8406d-5f65-4f7b-b669-13a6b7558c4f");
            _cityInfo = new RepoItemInfo(this, "CITY", "/dom[@domain='test.nursingworld.org']//input[#'CITY']", 30000, null, "896695ff-4e3c-48ac-bff3-0c37ab4d1d26");
            _zipcodeInfo = new RepoItemInfo(this, "Zipcode", "/dom[@domain='test.nursingworld.org']//div[#'address']/p[7]/input[@type='text']", 30000, null, "8d7b553d-4242-42f1-99a5-2d5db66c2703");
            _phone1Info = new RepoItemInfo(this, "phone1", "/dom[@domain='test.nursingworld.org']//div[#'phone']//input[@type='text']", 30000, null, "ddb23936-a5c8-40ce-9f4c-9b0569fd4db1");
            _phone2Info = new RepoItemInfo(this, "Phone2", "/dom[@domain='test.nursingworld.org']//div[#'phone']/div/span[2]/input[@type='text']", 30000, null, "b0c7beb4-2111-43f6-ac6a-28b366f5a7e1");
            _phone3Info = new RepoItemInfo(this, "phone3", "/dom[@domain='test.nursingworld.org']//div[#'phone']/div/span[3]/input[@type='text']", 30000, null, "4013150d-a8ef-4f37-81b3-f60f06945737");
            _newpasswordInfo = new RepoItemInfo(this, "NewPassword", "/dom[@domain='test.nursingworld.org']//div[#'content_area_main']/div/div[2]/div[1]/p[8]/input[@type='password']", 30000, null, "6f2015cd-58f3-4637-8d6d-d1018b3bf8d1");
            _confirmpasswordInfo = new RepoItemInfo(this, "ConfirmPassword", "/dom[@domain='test.nursingworld.org']//div[#'content_area_main']/div/div[2]/div[1]/p[9]/input[@type='password']", 30000, null, "10af4948-26e7-47b5-8f2a-8a99cbc1e9ee");
            _positiondescriptionInfo = new RepoItemInfo(this, "PositionDescription", "/dom[@domain='test.nursingworld.org']//div[#'radio_options']//select", 30000, null, "7e59c86c-1d0d-4799-a399-7902eea23378");
            _advancedpracticeInfo = new RepoItemInfo(this, "ADVANCEDPRACTICE", "/dom[@domain='test.nursingworld.org']//div[#'radio_options']//select/option[@value='ADVANCED_PRACTICE']", 30000, null, "be4deeaa-f030-43a1-b57d-0bc18e902fc7");
            _userregnextInfo = new RepoItemInfo(this, "Userregnext", "/dom[@domain='test.nursingworld.org']//a[#'userregnext']", 30000, null, "97f3a658-4c59-4dcd-8b4e-047b8a3392e7");
            _txtemailInfo = new RepoItemInfo(this, "TxtEmail", "/dom[@domain='test.nursingworld.org']//input[#'txtEmail']", 30000, null, "b64cc85a-0079-4857-9f4a-26f8faea2ab7");
            _btnnextInfo = new RepoItemInfo(this, "BtnNext", "/dom[@domain='test.nursingworld.org']//a[#'btnNext']", 30000, null, "7102ea50-58a4-49e0-b27e-378ad45ab8f2");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("03a5e1f6-ad4f-4699-9c4f-29b56a6c6347")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Lastname item.
        /// </summary>
        [RepositoryItem("908e1e9d-3481-4733-8b76-66c06151cafd")]
        public virtual Ranorex.InputTag Lastname
        {
            get
            {
                 return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The Lastname item info.
        /// </summary>
        [RepositoryItemInfo("908e1e9d-3481-4733-8b76-66c06151cafd")]
        public virtual RepoItemInfo LastnameInfo
        {
            get
            {
                return _lastnameInfo;
            }
        }

        /// <summary>
        /// The Firstname item.
        /// </summary>
        [RepositoryItem("c6d7db9f-f414-4d98-b2d0-e90913ae1a05")]
        public virtual Ranorex.InputTag Firstname
        {
            get
            {
                 return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The Firstname item info.
        /// </summary>
        [RepositoryItemInfo("c6d7db9f-f414-4d98-b2d0-e90913ae1a05")]
        public virtual RepoItemInfo FirstnameInfo
        {
            get
            {
                return _firstnameInfo;
            }
        }

        /// <summary>
        /// The AddressField1 item.
        /// </summary>
        [RepositoryItem("01a8406d-5f65-4f7b-b669-13a6b7558c4f")]
        public virtual Ranorex.InputTag AddressField1
        {
            get
            {
                 return _addressfield1Info.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The AddressField1 item info.
        /// </summary>
        [RepositoryItemInfo("01a8406d-5f65-4f7b-b669-13a6b7558c4f")]
        public virtual RepoItemInfo AddressField1Info
        {
            get
            {
                return _addressfield1Info;
            }
        }

        /// <summary>
        /// The CITY item.
        /// </summary>
        [RepositoryItem("896695ff-4e3c-48ac-bff3-0c37ab4d1d26")]
        public virtual Ranorex.InputTag CITY
        {
            get
            {
                 return _cityInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The CITY item info.
        /// </summary>
        [RepositoryItemInfo("896695ff-4e3c-48ac-bff3-0c37ab4d1d26")]
        public virtual RepoItemInfo CITYInfo
        {
            get
            {
                return _cityInfo;
            }
        }

        /// <summary>
        /// The Zipcode item.
        /// </summary>
        [RepositoryItem("8d7b553d-4242-42f1-99a5-2d5db66c2703")]
        public virtual Ranorex.InputTag Zipcode
        {
            get
            {
                 return _zipcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The Zipcode item info.
        /// </summary>
        [RepositoryItemInfo("8d7b553d-4242-42f1-99a5-2d5db66c2703")]
        public virtual RepoItemInfo ZipcodeInfo
        {
            get
            {
                return _zipcodeInfo;
            }
        }

        /// <summary>
        /// The phone1 item.
        /// </summary>
        [RepositoryItem("ddb23936-a5c8-40ce-9f4c-9b0569fd4db1")]
        public virtual Ranorex.InputTag phone1
        {
            get
            {
                 return _phone1Info.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The phone1 item info.
        /// </summary>
        [RepositoryItemInfo("ddb23936-a5c8-40ce-9f4c-9b0569fd4db1")]
        public virtual RepoItemInfo phone1Info
        {
            get
            {
                return _phone1Info;
            }
        }

        /// <summary>
        /// The Phone2 item.
        /// </summary>
        [RepositoryItem("b0c7beb4-2111-43f6-ac6a-28b366f5a7e1")]
        public virtual Ranorex.InputTag Phone2
        {
            get
            {
                 return _phone2Info.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The Phone2 item info.
        /// </summary>
        [RepositoryItemInfo("b0c7beb4-2111-43f6-ac6a-28b366f5a7e1")]
        public virtual RepoItemInfo Phone2Info
        {
            get
            {
                return _phone2Info;
            }
        }

        /// <summary>
        /// The phone3 item.
        /// </summary>
        [RepositoryItem("4013150d-a8ef-4f37-81b3-f60f06945737")]
        public virtual Ranorex.InputTag phone3
        {
            get
            {
                 return _phone3Info.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The phone3 item info.
        /// </summary>
        [RepositoryItemInfo("4013150d-a8ef-4f37-81b3-f60f06945737")]
        public virtual RepoItemInfo phone3Info
        {
            get
            {
                return _phone3Info;
            }
        }

        /// <summary>
        /// The NewPassword item.
        /// </summary>
        [RepositoryItem("6f2015cd-58f3-4637-8d6d-d1018b3bf8d1")]
        public virtual Ranorex.InputTag NewPassword
        {
            get
            {
                 return _newpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The NewPassword item info.
        /// </summary>
        [RepositoryItemInfo("6f2015cd-58f3-4637-8d6d-d1018b3bf8d1")]
        public virtual RepoItemInfo NewPasswordInfo
        {
            get
            {
                return _newpasswordInfo;
            }
        }

        /// <summary>
        /// The ConfirmPassword item.
        /// </summary>
        [RepositoryItem("10af4948-26e7-47b5-8f2a-8a99cbc1e9ee")]
        public virtual Ranorex.InputTag ConfirmPassword
        {
            get
            {
                 return _confirmpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The ConfirmPassword item info.
        /// </summary>
        [RepositoryItemInfo("10af4948-26e7-47b5-8f2a-8a99cbc1e9ee")]
        public virtual RepoItemInfo ConfirmPasswordInfo
        {
            get
            {
                return _confirmpasswordInfo;
            }
        }

        /// <summary>
        /// The PositionDescription item.
        /// </summary>
        [RepositoryItem("7e59c86c-1d0d-4799-a399-7902eea23378")]
        public virtual Ranorex.SelectTag PositionDescription
        {
            get
            {
                 return _positiondescriptionInfo.CreateAdapter<Ranorex.SelectTag>(true);
            }
        }

        /// <summary>
        /// The PositionDescription item info.
        /// </summary>
        [RepositoryItemInfo("7e59c86c-1d0d-4799-a399-7902eea23378")]
        public virtual RepoItemInfo PositionDescriptionInfo
        {
            get
            {
                return _positiondescriptionInfo;
            }
        }

        /// <summary>
        /// The ADVANCEDPRACTICE item.
        /// </summary>
        [RepositoryItem("be4deeaa-f030-43a1-b57d-0bc18e902fc7")]
        public virtual Ranorex.OptionTag ADVANCEDPRACTICE
        {
            get
            {
                 return _advancedpracticeInfo.CreateAdapter<Ranorex.OptionTag>(true);
            }
        }

        /// <summary>
        /// The ADVANCEDPRACTICE item info.
        /// </summary>
        [RepositoryItemInfo("be4deeaa-f030-43a1-b57d-0bc18e902fc7")]
        public virtual RepoItemInfo ADVANCEDPRACTICEInfo
        {
            get
            {
                return _advancedpracticeInfo;
            }
        }

        /// <summary>
        /// The Userregnext item.
        /// </summary>
        [RepositoryItem("97f3a658-4c59-4dcd-8b4e-047b8a3392e7")]
        public virtual Ranorex.ATag Userregnext
        {
            get
            {
                 return _userregnextInfo.CreateAdapter<Ranorex.ATag>(true);
            }
        }

        /// <summary>
        /// The Userregnext item info.
        /// </summary>
        [RepositoryItemInfo("97f3a658-4c59-4dcd-8b4e-047b8a3392e7")]
        public virtual RepoItemInfo UserregnextInfo
        {
            get
            {
                return _userregnextInfo;
            }
        }

        /// <summary>
        /// The TxtEmail item.
        /// </summary>
        [RepositoryItem("b64cc85a-0079-4857-9f4a-26f8faea2ab7")]
        public virtual Ranorex.InputTag TxtEmail
        {
            get
            {
                 return _txtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The TxtEmail item info.
        /// </summary>
        [RepositoryItemInfo("b64cc85a-0079-4857-9f4a-26f8faea2ab7")]
        public virtual RepoItemInfo TxtEmailInfo
        {
            get
            {
                return _txtemailInfo;
            }
        }

        /// <summary>
        /// The BtnNext item.
        /// </summary>
        [RepositoryItem("7102ea50-58a4-49e0-b27e-378ad45ab8f2")]
        public virtual Ranorex.ATag BtnNext
        {
            get
            {
                 return _btnnextInfo.CreateAdapter<Ranorex.ATag>(true);
            }
        }

        /// <summary>
        /// The BtnNext item info.
        /// </summary>
        [RepositoryItemInfo("7102ea50-58a4-49e0-b27e-378ad45ab8f2")]
        public virtual RepoItemInfo BtnNextInfo
        {
            get
            {
                return _btnnextInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("57498983-ee68-4f6d-b2a8-ef0ec2e7ff5a")]
        public virtual ANARepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Profile folder.
        /// </summary>
        [RepositoryFolder("13c65b4c-d861-48cf-928f-66b5ad3d7b74")]
        public virtual ANARepositoryFolders.ProfileFolder Profile
        {
            get { return _profile; }
        }

        /// <summary>
        /// The Login folder.
        /// </summary>
        [RepositoryFolder("6eedf114-e7b7-4aee-b825-28af62dcdc97")]
        public virtual ANARepositoryFolders.LoginAppFolder Login
        {
            get { return _login; }
        }

        /// <summary>
        /// The SelectingOptionInASelectListDrop folder.
        /// </summary>
        [RepositoryFolder("78946c15-2b98-47df-9419-e1a77fd1a34f")]
        public virtual ANARepositoryFolders.SelectingOptionInASelectListDropAppFolder SelectingOptionInASelectListDrop
        {
            get { return _selectingoptioninaselectlistdrop; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("89eb2975-c29b-47e7-bb82-99a0824c007a")]
        public virtual ANARepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class ANARepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("57498983-ee68-4f6d-b2a8-ef0ec2e7ff5a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            ANARepositoryFolders.MemberShip_PageFolder _membership_page;
            RepoItemInfo _joinanaInfo;
            RepoItemInfo _joinustodayInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='test.nursingworld.org']", parentFolder, 30000, null, false, "57498983-ee68-4f6d-b2a8-ef0ec2e7ff5a", "")
            {
                _membership_page = new ANARepositoryFolders.MemberShip_PageFolder(this);
                _joinanaInfo = new RepoItemInfo(this, "JoinANA", ".//body[#'top']/header/div/div[1]/div/div/div/div/div[2]/nav/ul/li[3]/a[@title='Join ANA']", 30000, null, "fb69a3ab-3d20-433d-95b7-f2331ae3fe5e");
                _joinustodayInfo = new RepoItemInfo(this, "JOINUSTODAY", ".//main[#'content']/div[1]/div[2]/div/div[3]/div[1]/p[3]/a[@innertext='JOIN US TODAY']", 30000, null, "baae085a-0244-406e-bef9-2dcdf9d6ab8e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("57498983-ee68-4f6d-b2a8-ef0ec2e7ff5a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("57498983-ee68-4f6d-b2a8-ef0ec2e7ff5a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JoinANA item.
            /// </summary>
            [RepositoryItem("fb69a3ab-3d20-433d-95b7-f2331ae3fe5e")]
            public virtual Ranorex.ATag JoinANA
            {
                get
                {
                    return _joinanaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JoinANA item info.
            /// </summary>
            [RepositoryItemInfo("fb69a3ab-3d20-433d-95b7-f2331ae3fe5e")]
            public virtual RepoItemInfo JoinANAInfo
            {
                get
                {
                    return _joinanaInfo;
                }
            }

            /// <summary>
            /// The JOINUSTODAY item.
            /// </summary>
            [RepositoryItem("baae085a-0244-406e-bef9-2dcdf9d6ab8e")]
            public virtual Ranorex.ATag JOINUSTODAY
            {
                get
                {
                    return _joinustodayInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The JOINUSTODAY item info.
            /// </summary>
            [RepositoryItemInfo("baae085a-0244-406e-bef9-2dcdf9d6ab8e")]
            public virtual RepoItemInfo JOINUSTODAYInfo
            {
                get
                {
                    return _joinustodayInfo;
                }
            }

            /// <summary>
            /// The MemberShip_Page folder.
            /// </summary>
            [RepositoryFolder("adcc0097-cad3-4890-b4b0-ece723c89a22")]
            public virtual ANARepositoryFolders.MemberShip_PageFolder MemberShip_Page
            {
                get { return _membership_page; }
            }
        }

        /// <summary>
        /// The MemberShip_PageFolder folder.
        /// </summary>
        [RepositoryFolder("adcc0097-cad3-4890-b4b0-ece723c89a22")]
        public partial class MemberShip_PageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnsavemembershipproductsInfo;

            /// <summary>
            /// Creates a new MemberShip_Page  folder.
            /// </summary>
            public MemberShip_PageFolder(RepoGenBaseFolder parentFolder) :
                    base("MemberShip_Page", "", parentFolder, 30000, null, false, "adcc0097-cad3-4890-b4b0-ece723c89a22", "")
            {
                _btnsavemembershipproductsInfo = new RepoItemInfo(this, "BtnSaveMemberShipProducts", ".//a[#'btnSaveMemberShipProducts']", 30000, null, "e48ec7b9-742e-4147-bed8-3c2a1fe26fa0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("adcc0097-cad3-4890-b4b0-ece723c89a22")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("adcc0097-cad3-4890-b4b0-ece723c89a22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnSaveMemberShipProducts item.
            /// </summary>
            [RepositoryItem("e48ec7b9-742e-4147-bed8-3c2a1fe26fa0")]
            public virtual Ranorex.ATag BtnSaveMemberShipProducts
            {
                get
                {
                    return _btnsavemembershipproductsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BtnSaveMemberShipProducts item info.
            /// </summary>
            [RepositoryItemInfo("e48ec7b9-742e-4147-bed8-3c2a1fe26fa0")]
            public virtual RepoItemInfo BtnSaveMemberShipProductsInfo
            {
                get
                {
                    return _btnsavemembershipproductsInfo;
                }
            }
        }

        /// <summary>
        /// The ProfileFolder folder.
        /// </summary>
        [RepositoryFolder("13c65b4c-d861-48cf-928f-66b5ad3d7b74")]
        public partial class ProfileFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ddlempstatusInfo;
            RepoItemInfo _stateInfo;

            /// <summary>
            /// Creates a new Profile  folder.
            /// </summary>
            public ProfileFolder(RepoGenBaseFolder parentFolder) :
                    base("Profile", "", parentFolder, 0, null, false, "13c65b4c-d861-48cf-928f-66b5ad3d7b74", "")
            {
                _ddlempstatusInfo = new RepoItemInfo(this, "DdlEmpStatus", "/dom[@domain='test.nursingworld.org']//select[#'ddlEmpStatus']", 30000, null, "5d4f48e2-82f5-4fdd-b442-07d45e4f8933");
                _stateInfo = new RepoItemInfo(this, "STATE", "/dom[@domain='test.nursingworld.org']//select[#'STATE']", 30000, null, "1faa8ac5-0ede-4033-81e9-abe6ae2aff80");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("13c65b4c-d861-48cf-928f-66b5ad3d7b74")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DdlEmpStatus item.
            /// </summary>
            [RepositoryItem("5d4f48e2-82f5-4fdd-b442-07d45e4f8933")]
            public virtual Ranorex.SelectTag DdlEmpStatus
            {
                get
                {
                    return _ddlempstatusInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DdlEmpStatus item info.
            /// </summary>
            [RepositoryItemInfo("5d4f48e2-82f5-4fdd-b442-07d45e4f8933")]
            public virtual RepoItemInfo DdlEmpStatusInfo
            {
                get
                {
                    return _ddlempstatusInfo;
                }
            }

            /// <summary>
            /// The STATE item.
            /// </summary>
            [RepositoryItem("1faa8ac5-0ede-4033-81e9-abe6ae2aff80")]
            public virtual Ranorex.SelectTag STATE
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The STATE item info.
            /// </summary>
            [RepositoryItemInfo("1faa8ac5-0ede-4033-81e9-abe6ae2aff80")]
            public virtual RepoItemInfo STATEInfo
            {
                get
                {
                    return _stateInfo;
                }
            }
        }

        /// <summary>
        /// The LoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("6eedf114-e7b7-4aee-b825-28af62dcdc97")]
        public partial class LoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "/dom[@domain='anatst2.personifycloud.com']", parentFolder, 30000, null, false, "6eedf114-e7b7-4aee-b825-28af62dcdc97", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "9ff41d4a-44a6-412d-a849-ebfeeb4779db");
                _loginInfo = new RepoItemInfo(this, "Login", ".//input[#'login']", 30000, null, "c5033e01-ceeb-4253-89fe-63a01a8531ba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6eedf114-e7b7-4aee-b825-28af62dcdc97")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6eedf114-e7b7-4aee-b825-28af62dcdc97")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("9ff41d4a-44a6-412d-a849-ebfeeb4779db")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("9ff41d4a-44a6-412d-a849-ebfeeb4779db")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("c5033e01-ceeb-4253-89fe-63a01a8531ba")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("c5033e01-ceeb-4253-89fe-63a01a8531ba")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The SelectingOptionInASelectListDropAppFolder folder.
        /// </summary>
        [RepositoryFolder("78946c15-2b98-47df-9419-e1a77fd1a34f")]
        public partial class SelectingOptionInASelectListDropAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _innerInfo;

            /// <summary>
            /// Creates a new SelectingOptionInASelectListDrop  folder.
            /// </summary>
            public SelectingOptionInASelectListDropAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectingOptionInASelectListDrop", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "78946c15-2b98-47df-9419-e1a77fd1a34f", "")
            {
                _innerInfo = new RepoItemInfo(this, "Inner", ".//div[#'page-body']/div[4]/div", 30000, null, "bb02e8a7-611f-4fa5-a7e3-aaf324cf17eb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("78946c15-2b98-47df-9419-e1a77fd1a34f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("78946c15-2b98-47df-9419-e1a77fd1a34f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Inner item.
            /// </summary>
            [RepositoryItem("bb02e8a7-611f-4fa5-a7e3-aaf324cf17eb")]
            public virtual Ranorex.DivTag Inner
            {
                get
                {
                    return _innerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Inner item info.
            /// </summary>
            [RepositoryItemInfo("bb02e8a7-611f-4fa5-a7e3-aaf324cf17eb")]
            public virtual RepoItemInfo InnerInfo
            {
                get
                {
                    return _innerInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("89eb2975-c29b-47e7-bb82-99a0824c007a")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fulltimeinnursingInfo;

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "89eb2975-c29b-47e7-bb82-99a0824c007a", "")
            {
                _fulltimeinnursingInfo = new RepoItemInfo(this, "FullTimeInNursing", "listitem[@accessiblename='Full Time in Nursing']", 30000, null, "5932d31a-2bb9-4e10-b7aa-7cf81e92c5e2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("89eb2975-c29b-47e7-bb82-99a0824c007a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("89eb2975-c29b-47e7-bb82-99a0824c007a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FullTimeInNursing item.
            /// </summary>
            [RepositoryItem("5932d31a-2bb9-4e10-b7aa-7cf81e92c5e2")]
            public virtual Ranorex.ListItem FullTimeInNursing
            {
                get
                {
                    return _fulltimeinnursingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The FullTimeInNursing item info.
            /// </summary>
            [RepositoryItemInfo("5932d31a-2bb9-4e10-b7aa-7cf81e92c5e2")]
            public virtual RepoItemInfo FullTimeInNursingInfo
            {
                get
                {
                    return _fulltimeinnursingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
