///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ANA.RecoderModules
{
    public partial class ProfilePage
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void selectOptionFromDrpdown(string argument1)
        {
           SelectTag someSelectTag = "/dom[@domain='test.nursingworld.org']//div[#'radio_options']//select";  
           OptionTag optTag = someSelectTag.FindSingle("./option[@value='ADVANCED_PRACTICE']");  
           optTag.Selected = true;  
        }

        public void selectStateFromDrpdown()
        {
           SelectTag someSelectTag = "/dom[@domain='test.nursingworld.org']//select[#'STATE']";  
           OptionTag optTag = someSelectTag.FindSingle("./option[@value='CA']");  
           optTag.Selected = true;  
        }

        public void selectDdlEmpStatus()
        {
           SelectTag someSelectTag = "/dom[@domain='test.nursingworld.org']//select[#'ddlEmpStatus']";  
           OptionTag optTag = someSelectTag.FindSingle("./option[@value='']");  
           optTag.Selected = true;  
        }
        
        

        
        
    }
}
